message("===================================================")
message("firelands Cata revision       : ${rev_hash} ${rev_date} (${rev_branch} branch)")
message("Build type            : ${CMAKE_BUILD_TYPE}")
message("Install server(s) to  : ${BIN_DIR}")
message("Install configs to    : ${CONF_INSTALL_DIR}")

message("")
message("Detailed Information")
message("+-- opeating system   : ${CMAKE_HOST_SYSTEM}")
message("+-- cmake version     : ${CMAKE_VERSION}")
message("")

if(BUILD_SERVER)
    message("Build worldserver     : Yes (default)")
    if(SCRIPT_LIB_ELUNA)
        message("+-- with Eluna script engine")
    endif()
    if(SCRIPT_LIB_SD3)
        message("+-- with SD3 script engine")
    endif()
    if(PLAYERBOTS)
        message("+-- with PlayerBots")
    endif()
else()
    message("Build worldserver     : No")
endif()

if(BUILD_AUTH)
    message("Build authserver    : Yes (default)")
else()
    message("Build authserver    : No")
endif()

if(SOAP)
    message("Support for SOAP      : Yes")
else()
    message("Support for SOAP      : No (default)")
endif()

if(BUILD_TOOLS)
    message("Build tools           : Yes (default)")
else()
    message("Build tools           : No")
endif()

if(WITHOUT_GIT)
  message("Use GIT revision hash   : No")
  message("")
  message(" *** WITHOUT_GIT - WARNING!")
  message(" *** Without Git installed, proper support may not be given.")
  message(" *** Some additional information that may be required, is only")
  message(" *** given when Git is enabled. Please install Git for support.")
else()
  message("Use GIT revision hash   : Yes (default)")
endif()

message("")
message("===================================================")
